version: '3.7'

services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8081:80"
        volumes:
            - ./html:/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - nginx-network
    php:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./html:/html
        networks:
            - nginx-network
    mysql-db:
        image: mysql:5.7
        restart: always
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - nginx-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
            PMA_HOST: mysql-db
            PMA_USER: root
            PMA_PASSWORD: mypassword
        ports:
            - "8082:80"
        networks:
            - nginx-network

volumes:
    mysql-data:

networks:
    nginx-network:
        driver: bridge

# MAINTAINER Pal Pal <palpal.tech@gmail.com>